src/blog/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),

]

src/posts/urls.py
from django.contrib.auth import views as auth_views, views
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path, include

from .views import TachesHome, TachesCreate, TachesUpdate, TachesDetail, TachesDelete, signup, logout_view
from django.contrib.auth.decorators import login_required

app_name = "posts"


urlpatterns = [
    path('', signup, name="signup"),
    path('login/home/', login_required(TachesHome.as_view()), name="acceuil"),
    path("login/", LoginView.as_view(), name="login"),
    path('logout/', logout_view, name='logout'),
    path('add/', login_required(TachesCreate.as_view()), name="add"),
    path('<str:pk>/', login_required(TachesDetail.as_view()), name="post"),
    path('edit/<str:pk>/', login_required(TachesUpdate.as_view()), name="edit"),
    path('delete/<str:pk>/', login_required(TachesDelete.as_view()), name="delete")
]


src/posts/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse



# Create your models here.

class MyUserManager(BaseUserManager):
    def create_user(self, username, password=None):
        if not username:
            raise ValueError("Vous devez entrer un nom utilisateur.")
        username = self.model.normalize_username(username)
        user = self.model(
            username=username
        )
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, password=None):
        user = self.create_user(username=username, password=password)
        user.is_staff = True
        user.is_allowed = True
        user.save()
        return user

class CustomUser(AbstractBaseUser):
    username = models.CharField(
        unique=True,
        max_length= 50,
        blank=False
    )
    is_staff = models.BooleanField(default=False)
    is_allowed = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)


    USERNAME_FIELD = "username"
    objects = MyUserManager()

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True



class Tache(models.Model):
    title = models.CharField(max_length=150, unique = True, verbose_name="Tache")
    responsable = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True)
    description = models.TextField()
    date_de_debut = models.DateField()
    date_de_fin = models.DateField(blank=True, null=True)
    priorite = models.CharField(max_length=20, choices=[
        ('absolue', 'Absolue'),
        ('haute', 'Haute'),
        ('moyenne', 'Moyenne'),
        ('basse', 'Basse'),
    ])
    statut = models.CharField(max_length=20)
    avancement = models.IntegerField(default=0)
    commentaires = models.TextField()

    class Meta:
        ordering = ['-date_de_debut']
        verbose_name = "Tache"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:acceuil')



src/posts/forms.py
from django import forms
from posts.models import Tache


class TacheForm(forms.ModelForm):
    class Meta:
        model = Tache
        fields = [
            'title', 'description', 'date_de_debut', 'date_de_fin', 'priorite', 'statut', 'avancement', 'commentaires'
        ]
        widgets = {
            'date_de_debut':forms.DateTimeInput(attrs={'type': 'date'}),
            'date_de_fin': forms.DateInput(attrs={'type': 'date'}),
        }


class TacheForm_(forms.ModelForm):
    class Meta:
        model = Tache
        fields = [
            'title', 'description', 'priorite', 'statut', 'avancement', 'commentaires'
        ]


src/posts/views.py
from gc import get_objects

from django.contrib.auth import logout

from django.shortcuts import render
from django.urls import reverse_lazy

# Create your views here.

from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from posts.forms import TacheForm, TacheForm_
from posts.models import Tache, CustomUser


class TachesHome(ListView):
    model = Tache
    context_object_name = "posts"

class TachesCreate(CreateView):
    model = Tache
    form_class = TacheForm
    template_name = "posts/tache_create.html"

    def form_valid(self, form):
        form.instance.responsable = self.request.user
        return super().form_valid(form)
#

class TachesUpdate(UpdateView):
    model = Tache
    template_name = "posts/tache_edit.html"

    form_class = TacheForm_


class TachesDetail(DetailView):
    model = Tache
    context_object_name = "post"


class TachesDelete(DeleteView):
    model = Tache
    context_object_name = "post"
    success_url = reverse_lazy("posts:acceuil")


def signup(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")
        if password1 != password2:
            return render(request, "posts/signup.html", {"error": "Les mots de passe ne colent pas"})

        CustomUser.objects.create_user(username=username, password=password1)
        return render(request,'posts/tache_list.html')
    return render(request, "posts/signup.html")


def logout_view(request):
    logout(request)
    return render(request, 'posts/signup.html')

src/posts/templates/posts/signup.html

{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>SoftPlanetCompany</title>
    {% endblock  %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="main" id="blog">
    <div class="rest">

<h3>S'inscrire</h3>
<form method="POST">
    {% csrf_token %}
    <label for="username">Username</label>
    <input type="text" name="username" id="username">
    <label for="password1">Mot de passe</label>
    <input type="password" name="password1" id="password1">
    <label for="password2">Confirmation</label>
    <input type="password" name="password2" id="password2">
    {% if error %}
    <small style="color: red;">
        {{ error }}
    </small>
    {% endif %}
    {% if ext %}
    <small style="color: green;">
        {{ ext }}
    </small>
    {% endif %}
    <br>
    <input type="submit" value="S'inscrire">
    </form>
        <br>
        <a href="{% url 'posts:login' %}">Cliquer ici pour aller se connecter</a>
    </div>
</div>

</body>
</html>

src/posts/templates/posts/tache_confirm_delete.html
{% extends 'base.html' %}
{% block title %}
<title>Supprimer une tache</title>
{% endblock %}
{% block content %}
<h1>Ajouter une tache</h1>
<form method="POST">
    {% csrf_token %}
    <p>Etes-vous sur de vouloir supprimer "{{ post }}"</p>
  <input type="submit" value="Oui, supprimer" class="btn btn-delete">
</form>


{% endblock %}

src/posts/templates/posts/tache_create.html
{% extends 'base.html' %}

{% block title %}
<title> Ajouter une tache </title>
{% endblock %}

{% block content %}


<h2>Ajouter une tache</h2>
<form method="POST">
    {% csrf_token %}
    {{ form }}
  <input type="submit" value="Ajouter" class="btn btn-submit">
</form>


{% endblock %}

src/posts/templates/posts/tache_detail.html
{% extends 'base.html' %}

{% block title %}
<title> {{ post.title }} </title>
{% endblock %}

{% block content %}

<article class="post-detail">
  <h2>Tache:<br>{{ post.title }}</h2>
  <ul>
    <li> <strong>Priorité :</strong> {{ post.priorite }}</li>
    <br>
    <li><strong>Responsable : {{ post.responsable }}</strong></li>
    <br>
    <li><strong>Avancement :</strong> {{ post.avancement }}%</li>
    <li> <strong>Date de debut :</strong>  {{ post.date_de_debut }}</li>
    <li><strong>Date de fin :</strong>  {{ post.date_de_fin }}</li>
    <li><strong>Statut :</strong> {{ post.statut }}</li>
  </ul>

  <p><strong>Description:</strong><br> {{ post.description }}</p>
  <p><strong>Commentaires:</strong><br> {{ post.commentaires }}</p>

</article>


{% endblock %}

src/posts/templates/posts/tache_edit.html
{% extends 'base.html' %}

{% block title %}
<title> Editer une tache </title>
{% endblock %}

{% block content %}


<h1>Mettez à jour votre tache</h1>
<form method="POST">
    {% csrf_token %}
    {{ form }}
  <input type="submit" value="Editer" class="btn btn-submit">
</form>


{% endblock %}

src/posts/templates/posts/tache_list.html
{% extends 'base.html' %}

{% block title %}
<title> List des taches </title>
{% endblock %}

{% block content %}


<h2>{{ request.user.username }} Connecté</h2>
    <article>
        <div class="tablesection">
            <table class="table">
            <thead>
                <tr>
                    <th>Tache</th>
                    <th>Description</th>
                    <th>Responsable</th>
                    <th>Date de debut</th>
                    <th>Date de fin</th>
                    <th>Priorite</th>
                    <th>Statut</th>
                    <th>Avancement</th>
                    <th>commentaires</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% if request.user.is_allowed %}
                {% for post in posts %}
        <tr>
            <td>
                <a href="{% url 'posts:post' pk=post.pk %}" class="edit">
                    {{ post.title }}
                </a>
            </td>
            <td>{{ post.description|safe|truncatewords:5 }}</td>
            <td><strong>{{ post.responsable.username }}</strong></td>
            <td>{{ post.date_de_debut }}</td>
            <td>{{ post.date_de_fin }}</td>
            <td>{{ post.priorite }}</td>
            <td>{{ post.statut }}</td>
            <td>{{ post.avancement }}</td>
            <td>{{ post.commentaires|safe|truncatewords:4 }}</td>
            <td>
                <div class="actions">
                    {% if request.user.is_authenticated and request.user == post.responsable %}
                        <a href="{% url 'posts:edit' pk=post.pk %}" class="edit">Editer</a>
                        {% if request.user.is_staff %}
                            <a href="{% url 'posts:delete' pk=post.pk %}" class="delete">Supprimer</a>
                        {% endif %}
                    {% endif %}
                </div>
            </td>

        </tr>
        {% endfor %}
            {% endif %}
            </tbody>
        </table>
        </div>
    </article>


{% endblock %}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>SoftPlanetCompany</title>
    {% endblock  %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<nav>
    <h2>Soft_Planet_Company</h2>
    <div class="options">
        <a href="{% url 'posts:acceuil' %}" class="-">Acceuil</a>
        {% if request.user.is_authenticated and request.user.is_allowed %}
        <a href="{% url 'posts:add' %}" class="-">Ajouter</a>
        {% endif %}
        <a href="{% url 'posts:logout' %}">Se déconnecter</a>
    </div>
</nav>

<div class="main" id="blog">
    <div class="rest">
        {% block content %}
        {% endblock %}
    </div>

</div>

</body>
</html>